### ISSUE TITLE
Making general corrections to improve the files

### ISSUE THREAD

**Issue by Mehrab-Atighi** [efmp00/my-latex-templates#1]
Hello, 
at the first i want say thanks for your sharing. 
then
i think you need to two change to your files . 
first format.tex file please attention that you're using `\begin{problem}` and it need to this change:
(remove a from problema)
```
\newtcbtheorem[]{**problema**}{Problem}%
    {enhanced,
    colback = black!5, %white,
    colbacktitle = black!5,
    coltitle = black,
    boxrule = 0pt,
    frame hidden,
    borderline west = {0.5mm}{0.0mm}{black},
    fonttitle = \bfseries\sffamily,
    breakable,
    before skip = 3ex,
    after skip = 3ex
}{**problema**}
```
the problema should be problem to work.

the second is that you are using `\input{problems/P1} ` in main.tex file and there is no problems folder and P1.tex file please add it or change the main.tex and add youre text to that.
i  uploaded my main.tex and edited format.tex.
thanks.
[Mathematics-HW-template.zip](https://github.com/user-attachments/files/17161001/Mathematics-HW-template.zip)

**Comment by efmp00** [comment]
Dear Mehrab-Atighi:

Thank you for your suggestions! I've made the requested improvements. I also uploaded a better PDF example version and a "note.md" file where anyone can access the template directly in Overleaf. I'll close this issue in the upcoming days if there is nothing else to fix.
